baseURL = "https://marikgoldstein.github.io"
languageCode = "en-us"
title = "Mark Golstein"
theme = "onetwothree"
pygmentsCodeFences = true
pygmentsStyle = "autumn"

[permalinks]
    posts = "/:slug/"

[params]
    email = "rachitsingh@college.harvard.edu"
    navigation = ["about.md", "links.md"]
