baseURL = "https://marikgoldstein.github.io"
languageCode = "en-us"
title = "Mark Goldstein"
theme = "onetwothree"
pygmentsCodeFences = true
pygmentsStyle = "autumn"

[permalinks]
    posts = "/:slug/"

[params]
    email = "goldstein@nyu.edu"
    navigation = ["about.md", "links.md"]
